### ISSUE TITLE
Guard Walk AI

### ISSUE THREAD

**Issue by shawnmacburnie** [Glavin001/battlecode#11]
Needs to not walk within 2 spaces of an arcon so it doesn't get in the way of new spawning. As well as have a max distance from arcon.

**Comment by LizardLeliel** [comment]
I think a good max distance would be max sight range.

In other words, a guard will always need to be in sight of an archon. If an archon goes out of sight, then it can move towards the last known archon position.

**Comment by Glavin001** [comment]
@sookool99 maybe you and I should discuss what functions you plan to use/implement.
I may have already written them elsewhere and/or I may also find those functions useful and can use for Viper and Turret code.
