### ISSUE TITLE
Avoid building Vipers?

### ISSUE THREAD

**Issue by LizardLeliel** [Glavin001/battlecode#14]
Vipers have some pretty unique properties, such as a damage-over-time that turns enemies into zombies.

However, the cost for them is very high; according to http://s3.amazonaws.com/battlecode-releases-2016/lectures/Battlecode2016SimplifiedSpecs_160106.pdf the parts need to build them is 100, while turrets require 75 and most only need around 20 or so. They're attack is 2, which is half of a solider, and they only have the same range. They do more health then a soldier, and the same attack range - however for the price of 1 viper we can build 5 soldiers who will have an overall attack power of 20.

And while zombies do pose a risk for the enemy, they pose just as much pose for our team.

**Comment by Glavin001** [comment]
See #8 for Viper attack strategy that the rest of us discussed.

I do agree that we should not prioritize building Vipers unless we are in a comfortable situation in terms of parts, etc.

**Comment by Glavin001** [comment]
Vipers are now very strategic: their attack range is more than soldiers and they can pick in and out of their range. See http://s3.amazonaws.com/battlecode-releases-2016/releases/specs-0.1.1.html#bcd15
