### ISSUE TITLE
Cannot broadcast more than 20 message signals per turn

### ISSUE THREAD

**Issue by shawnmacburnie** [Glavin001/battlecode#21]
We either need to Catch this somewhere or Not send so many signals. We are throwing this error killing the bots are blowing up.

**Comment by Glavin001** [comment]
@CameronFc fixed this. Just waiting on his final push :smile:

**Comment by CameronFc** [comment]
Fixed in next update. All messaging is routed through Messaging.sendMessage(message, squaredRadius).

**Comment by Glavin001** [comment]
![image](https://cloud.githubusercontent.com/assets/1885333/12326155/55416c7e-baa5-11e5-82a7-8dbd18c229a0.png)
